// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQsbUXwzoPqzSuEhR6d_-Ow-Rj8kan5fc',
    appId: '1:607512237792:web:61523e52402fe85d70e285',
    messagingSenderId: '607512237792',
    projectId: 'xpapp-b451c',
    authDomain: 'xpapp-b451c.firebaseapp.com',
    storageBucket: 'xpapp-b451c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv9CZal69c_Vqlmm3AjqBQaVMMNhLwgs8',
    appId: '1:607512237792:android:5fcf3febdacf512870e285',
    messagingSenderId: '607512237792',
    projectId: 'xpapp-b451c',
    storageBucket: 'xpapp-b451c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4M-QlXTK-LS1QWBCidXq90vqb1TuzW8k',
    appId: '1:607512237792:ios:b8747707e78debbd70e285',
    messagingSenderId: '607512237792',
    projectId: 'xpapp-b451c',
    storageBucket: 'xpapp-b451c.firebasestorage.app',
    iosBundleId: 'com.example.xpapp',
  );
}
